ifdef::env-github[]
To read this tutorial fully rendered, please visit: https://ahus1.github.io/keycloak-dropwizard-integration/tutorial.html.
endif::[]

# Preparing a proper Dropwizard Bundle for Keycloak

## What you can see here

This is a Dropwizard bundle that provides a ready-to-use Keycloak integration.

## Step by Step

This shows the main integration points

. Setup keycloak as an Authenticator to handle pre-auth integration:
+
[source,java,indent=0]
.KeycloakBundle.java
-----
include::src/main/java/de/ahus1/keycloak/dropwizard/KeycloakBundle.java[tags=authenticator]
-----

. Setup the authentication factory
+
[source,java,indent=0]
.KeycloakBundle.java
-----
include::src/main/java/de/ahus1/keycloak/dropwizard/KeycloakBundle.java[tags=authfactory]
-----

## How to use it

To use it:

. register the _KeycloakBundle_
. override _getKeycloakConfiguration()_ to provide the configuration information.

Optionally (if you want to use a different class instead of _User_ to wrap access to Keycloak):

. override _getUserClass()_ to return the class you are using
. override _createAuthenticator()_ to provide a factory to create the instances of your user class
. override _createAuthorizer()_ to implement the role checking used by the _@RolesAllowed_ annotation.

See the default implementations _User_, _KeycloakAuthenticator_, and _UserAuthorizer_ as a guide.

Please see the next chapter how to integrate.

