ifdef::env-github[]
To read this tutorial fully rendered, please visit: https://ahus1.github.io/keycloak-dropwizard-integration/tutorial.html.
endif::[]

# Preparing a proper Dropwizard Bundle for Keycloak

## What you can see here

This is a Dropwizard bundle that provides a ready-to-use Keycloak integration.

## Step by Step

This shows the main integration points

. Setup keycloak as an Authentication Handler in Dropwizard style:
+
[source,java,indent=0]
.KeycloakBundle.java
-----
include::src/main/java/de/ahus1/keycloak/dropwizardjaxrs/KeycloakBundle.java[tags=keycloak]
-----


. Setup security constraint handler
+
[source,java,indent=0]
.KeycloakBundle.java
-----
include::src/main/java/de/ahus1/keycloak/dropwizardjaxrs/KeycloakBundle.java[tags=constraint]
-----

## How to use it

Anyone who wants to use this will need register this bundle and will need to provide an own implementation derived from `AbstractKeycloakAuthenticator` together with an class encapsulating the user's authentication that might be derived from `Authentication`. Please see the next chapter how to integrate.

