ifdef::env-github[]
To read this tutorial fully rendered, please visit: https://ahus1.github.io/keycloak-dropwizard-integration/tutorial.html.
endif::[]

= Simple Dropwizard Integration Servlet style

== What you can see here

This is a very simple Dropwizard application setup using Freemarker as templating.

== Setup for Keycloak

The following elements add Keycloak authentication to Dropwizard:

. Add Keycloak information to `config.yml`
+
[source,yaml,indent=0]
.config.yml
-----
include::../config.yml[tags=config]
-----
. Add Keycloak to `LotteryConfiguration.java`
+
[source,java,indent=0]
.LotteryConfiguration.java
-----
include::src/main/java/de/ahus1/lottery/adapter/dropwizard/LotteryConfiguration.java[tags=config]
-----
. Setup security constraint previously setup in `web.xml`, now in `LotteryApplication.java`
+
[source,java,indent=0]
.LotteryApplication.java
-----
include::src/main/java/de/ahus1/lottery/adapter/dropwizard/LotteryApplication.java[tags=constraint]
-----
. Setup keycloak previously setup in `jetty-web.xml`, now in `LotteryApplication.java`
+
[source,java,indent=0]
.LotteryApplication.java
-----
include::src/main/java/de/ahus1/lottery/adapter/dropwizard/LotteryApplication.java[tags=keycloak]
-----

////
## Additions to handle user roles in ressources

TODO: describe @Role annotation and how to activate it.
////

== How to run

Use the following command line to start it from the parent's directory

----
mvn test -pl keycloak-dropwizard-jetty -am -Pkeycloak-dropwizard-jetty
----

Once it is started, point your browser to http://localhost:9090 to see the application.

Enter a date like `2015-01-01` to see the predicted results of the given date.