ifdef::env-github[]
To read this tutorial fully rendered, please visit: https://ahus1.github.io/keycloak-dropwizard-integration/tutorial.html.
endif::[]

# Dropwizard Integration for Bearer-Only REST services with Dropwizard Module

## What you can see here

This is a setup that includes a small JavaScript client that interfaces with a REST backend.
The client authenticates all requests using a Bearer Token.

The different to the example `keycloak-dropwizard-bearer` is here that the keycloak-dropwizard module is used in this example.

## Setup for Keycloak

The following elements add Keycloak authentication to Dropwizard and are identical to the simple setup:

. Add Keycloak `config-bearer.yml` with bearer only authentication. This way the Keycloak will not
initiate the OAuth redirecting flow. And the Keycloak Dropwiazrd module with not interfere with any
OAuth redirect initiated by the frontend.
+
[source,yaml,indent=0]
.config-bearer.yml
-----
include::../config-bearer.yml[tags=bearer-a]
include::../config-bearer.yml[tags=bearer-b]

-----
. Add Keycloak as a security constraint to `LotteryConfiguration.java`, but without the role and URL mappings.
+
[source,java,indent=0]
.LotteryConfiguration.java
-----
include::src/main/java/de/ahus1/lottery/adapter/dropwizard/LotteryConfiguration.java[tags=config]
-----
. Add Keycloak as a filter to the REST stack.
+
WARNING: Be aware that all calls to REST ressources now require a Bearer Token. There are no unauthenticated requests any more (except to static ressources)
+
[source,java,indent=0]
.LotteryApplication.java
-----
include::src/main/java/de/ahus1/lottery/adapter/dropwizard/LotteryApplication.java[tags=keycloak]
-----

A very short and simple JavaScript client is located in `src/main/ressources/assets/ajax`.

## How to run

Use the following command line to start it from the parent's directory

----
mvn test -pl keycloak-dropwizard-bearermodule -am -Pkeycloak-dropwizard-bearermodule
----

Once it is started, point your browser to http://localhost:9090/ajax/index.html to see the application.

Enter a date like `2015-01-01` to see the predicted results of the given date.