ifdef::env-github[]
To read this tutorial fully rendered, please visit: https://ahus1.github.io/keycloak-dropwizard-integration/tutorial.html.
endif::[]

# Dropwizard Integration for Bearer-Only REST services

## What you can see here

This is a setup that includes a small JavaScript client that interfaces with a REST backend.
The client authenticates all requests using a Bearer Token.

## Setup for Keycloak

The following elements add Keycloak authentication to Dropwizard and are identical to the simple setup:

. Add Keycloak information to `config.yml`
+
[source,yaml,indent=0]
.config.yml
-----
include::../config.yml[tags=config-a]
  realmKey: "MIIB...AQAB"
include::../config.yml[tags=config-b]
-----
. Add Keycloak as a security constraint to `LotteryConfiguration.java`, but without the role and URL mappings.
+
[source,java,indent=0]
.LotteryConfiguration.java
-----
include::src/main/java/de/ahus1/lottery/adapter/dropwizard/LotteryConfiguration.java[tags=config]
-----
. Add Keycloak as a filter to the REST stack.
+
WARNING: Be aware that all calls to REST ressources now require a Bearer Token. There are no unauthenticated requests any more (except to static ressources)
+
[source,java,indent=0]
.LotteryApplication.java
-----
include::src/main/java/de/ahus1/lottery/adapter/dropwizard/LotteryApplication.java[tags=keycloak]
-----

A very short and simple JavaScript client is located in `src/main/ressources/assets/ajax`.

## How to run

Use the following command line to start it from the parent's directory

----
mvn test -pl keycloak-dropwizard-bearer -am -Pkeycloak-dropwizard-bearer
----

Once it is started, point your browser to http://localhost:9090/ajax/index.html to see the application.

Enter a date like `2015-01-01` to see the predicted results of the given date.