ifdef::env-github[]
To read this tutorial fully rendered, please visit: https://ahus1.github.io/keycloak-dropwizard-integration/tutorial.html.
endif::[]

# Keycloak enabled Web Application

## What you can see here

This is the sample application as `simple-war`, but now it has been enhanced to support login via Keycloak.

## Things that have been added for Keycloak

The following bits and piece have been added to the application as described in the Keycloak manual:

. Additions to `web.xml`
+
[source,xml,indent=0]
.web.xml
-----
include::src/main/webapp/WEB-INF/web.xml[tags=security]
-----
. New file `jetty-web.xml`
+
[source,xml,indent=0]
.jetty-web.xml
-----
include::src/main/webapp/WEB-INF/jetty-web.xml[]
-----
. `keycloak.json` to hold keycloak configuration
. Addition to `DrawServlet` to show principal information
+
[source,java,indent=0]
.DrawServlet.java
-----
include::src/main/java/de/ahus1/lottery/adapter/servlet/DrawServlet.java[tags=principal]
-----
. Addition to `index.ftl` to show principal information and to allow logout
+
[source,freemarker,indent=0]
.index.ftl
-----
include::src/main/webapp/index.ftl[tags=principal]
-----
. `logout.tfl` to show a logout page
. `LogoutServlet.java` to support logout
+
[source,java,indent=0]
.LogoutServlet.java
-----
include::src/main/java/de/ahus1/lottery/adapter/servlet/LogoutServlet.java[tags=logout]
-----

## How to run

Please startup Keycloak as described in the introduction.

Use the following command line to start the application from the parent's directory

----
mvn test -pl keycloak-war -am -Pkeycloak-war
----

Once it is started, point your browser to http://localhost:9090 to see the application.

You'll be redirected to the Keycloak login screen. Use username `demo` and password `demo` to log in.

Enter a date like `2015-01-01` to see the predicted results of the given date.

